// <auto-generated />
using CustomerChurn.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerChurn.Server.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomerChurn.Server.Data.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("char(10)");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Dependents")
                        .HasColumnType("bit");

                    b.Property<string>("DeviceProtection")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Gender")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("InternetService")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<decimal>("MonthlyCharges")
                        .HasColumnType("money");

                    b.Property<string>("MultipleLines")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("OnlineBackup")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("OnlineSecurity")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<bool>("PaperlessBilling")
                        .HasColumnType("bit");

                    b.Property<bool>("Partner")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneService")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<bool>("SeniorCitizen")
                        .HasColumnType("bit");

                    b.Property<string>("StreamingMovies")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("StreamingTV")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("TechSupport")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCharges")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
